name: Blackduck scan

on:
  schedule:
    - cron: '30 5 * * 0'   

jobs:
  blackduck-scan:
    runs-on: azure-runners
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
         node-version: 16
      - run: npm install --package-lock
      
      - name: Scan Blackduck
        uses: synopsys-sig/detect-action@v0.3.0
        env:
            LOGGING_LEVEL_DETECT: INFO
            DETECT_TIMEOUT: 60
        with:
            scan-mode: RAPID
            github-token: ${{ secrets.GITHUB_TOKEN }}
            detect-version: 7.14.0
            blackduck-url: https://bdscan.i.mercedes-benz.com/
            blackduck-api-token: ${{ secrets.BLACKDUCKSCAN_TOKEN }}
            fail-on-all-policy-severities: true
